document.addEventListener('DOMContentLoaded',()=>{
 const side=document.querySelector('.sidebar'),back=document.querySelector('.backdrop');
 const close=()=>{side?.classList.remove('open');back?.classList.remove('show');document.body.style.overflow=''};
 document.querySelector('[data-menu]')?.addEventListener('click',()=>{side?.classList.add('open');back?.classList.add('show');document.body.style.overflow='hidden'});back?.addEventListener('click',close);
 const page=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav a').forEach(a=>{if(a.getAttribute('href')===page)a.classList.add('active');a.addEventListener('click',()=>innerWidth<768&&close())});
 const range=document.querySelector('#urgency'),out=document.querySelector('#urgencyValue');if(range&&out){const u=()=>out.value=range.value;range.addEventListener('input',u);u()}
 const grid=document.querySelector('#doctorGrid');if(grid){const cards=[...grid.querySelectorAll('[data-doctor]')],q=document.querySelector('#doctorSearch'),d=document.querySelector('#doctorDepartment'),count=document.querySelector('#doctorCount'),empty=document.querySelector('#doctorEmpty');const f=()=>{let n=0,Q=(q?.value||'').toLowerCase(),D=(d?.value||'').toLowerCase();cards.forEach(c=>{let ok=(!Q||c.textContent.toLowerCase().includes(Q))&&(!D||(c.dataset.department||'').toLowerCase().includes(D));c.classList.toggle('hidden',!ok);if(ok)n++});if(count)count.textContent=`${n} doctor${n===1?'':'s'} shown`;empty?.classList.toggle('hidden',n!==0)};q?.addEventListener('input',f);d?.addEventListener('change',f);f()}
 const form=document.querySelector('#appointmentForm'),modal=document.querySelector('#confirmationModal'),ref=document.querySelector('#bookingRef'),toast=document.querySelector('#toast');const toastShow=(a,b)=>{if(!toast)return;toast.innerHTML=`<b>${a}</b><span>${b}</span>`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),4000)};document.querySelector('[data-modal-close]')?.addEventListener('click',()=>modal?.classList.remove('show'));modal?.addEventListener('click',e=>e.target===modal&&modal.classList.remove('show'));
 form?.addEventListener('reset',()=>setTimeout(()=>{if(range&&out)out.value=range.value},0));form?.addEventListener('submit',e=>{e.preventDefault();if(!form.checkValidity()){form.reportValidity();toastShow('Please check the form','Complete required fields and try again.');return}let r=`KLE-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;if(ref)ref.textContent=r;modal?.classList.add('show');toastShow('Request created',`Reference ${r}`)});
});
